[package]
name = "printer_bot_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
brother_ql = { path="../brother_ql" }
dotenvy = "0.15.7"
env_logger = "0.11.8"
log = "0.4.20"
teloxide-core = "0.13"
thiserror = "2.0.16"
tokio = { version = "1.34.0", features = ["full"] }
